scoreboard-title: '&c&lWanted Levels'
scoreboard-name: '&6{stars} &b{player}'
tab-list-name: '&6{stars} &5{player}'
jail-command: '/jail {player} jailOne'
stars-per-kills:
    - 1
    - 3
    - 5
    - 10
    - 20
kills: {}